# Combine the MAGs
cat binning/final_MAGs/mealworm/*.fasta > MAG_abundance/Mealworm_MAGs_combined.fasta
cat binning/final_MAGs/superworm/*.fasta > MAG_abundance/Superworm_MAGs_combined.fasta 

# Change directory
cd MAG_abundance/

# Build bowtie2 databases
bowtie2-build --threads 24 Mealworm_MAGs_combined.fasta mealworm_MAGs_database
bowtie2-build --threads 24 Superworm_MAGs_combined.fasta superworm_MAGs_database

# Map reads with bowtie mealworm
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_1a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_1a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_1a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_1b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_1b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_1b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_2a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_2a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_2a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_2b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_2b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_2b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_3a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_3a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_3a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Control_3b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Control_3b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Control_3b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_1a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_1a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_1a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_1b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_1b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_1b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_2a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_2a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_2a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_2b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_2b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_2b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_3a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_3a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_3a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_PB_3b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_PB_3b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_PB_3b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_1a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Standard_1a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Standard_1a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_2a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Standard_2a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Standard_2a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_2b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Standard_2b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Standard_2b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Standard_3a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Standard_3a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Standard_3a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_1a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_1a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_1a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_1b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_1b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_1b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_2a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_2a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_2a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_2b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_2b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_2b.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_3a_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_3a.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_3a.bam
bowtie2 -p 24 --no-unal -x mealworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/mealworm_Styrofoam_3b_R2.cleaned.fastq.gz 2> Mealworm_MAGs_combined_Styrofoam_3b.txt | samtools view -Sb -@ 4 -o Mealworm_MAGs_combined_Styrofoam_3b.bam

# Map reads with bowtie superworm
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_1a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_1a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_1a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_1b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_1b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_1b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_2a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_2a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_2a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_2b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_2b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_2b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_3a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_3a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_3a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Control_3b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Control_3b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Control_3b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_1a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_1a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_1a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_1b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_1b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_1b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_2a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_2a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_2a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_2b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_2b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_2b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_3a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_3a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_3a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_PB_3b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_PB_3b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_PB_3b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_1a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_1a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_1a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_1b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_1b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_1b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_2a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_2a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_2a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_2b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_2b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_2b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_3a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_3a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_3a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Standard_3b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Standard_3b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Standard_3b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_1a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_1a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_1a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_1a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_1b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_1b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_1b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_1b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_2a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_2a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_2a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_2a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_2b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_2b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_2b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_2b.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_3a_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_3a_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_3a.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_3a.bam
bowtie2 -p 24 --no-unal -x superworm_MAGs_database -1 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_3b_R1.cleaned.fastq.gz -2 /datadisk1/Users/Sabhjeet/metagenomics/read_preprocessing/cleaned_reads/superworm_Styrofoam_3b_R2.cleaned.fastq.gz 2> Superworm_MAGs_combined_Styrofoam_3b.txt | samtools view -Sb -@ 4 -o Superworm_MAGs_combined_Styrofoam_3b.bam

# Go back to working directory
cd ../

# Get overall mapping rates
grep 'overall' MAG_abundance/*.txt > MAG_abundance/mapping_rate.txt

# Get sample and MAG names
ls -1 MAG_abundance/ | grep 'Mealworm' | grep 'bam' | sed 's/\.bam//' > MAG_abundance/mealworm_sample_names.txt
ls -1 MAG_abundance/ | grep 'Superworm' | grep 'bam' | sed 's/\.bam//' > MAG_abundance/superworm_sample_names.txt
grep '>' MAG_abundance/Mealworm_MAGs_combined.fasta | sed 's/>//' | sed 's/_contig_/\t/' | cut -f1,1 | sort -u > MAG_abundance/mealworm_MAG_names.txt
grep '>' MAG_abundance/Superworm_MAGs_combined.fasta | sed 's/>//' | sed 's/_contig_/\t/' | cut -f1,1 | sort -u > MAG_abundance/superworm_MAG_names.txt

# Get MAG abundances
cd MAG_abundance/
perl ../scripts/getAbundance_mealworm.pl
perl ../scripts/getAbundance_superworm.pl
perl ../scripts/getAbundance_mealworm_2.pl
perl ../scripts/getAbundance_superworm_2.pl
cd ../